use_gpu: True
device: 0
data:
  root: data/
  type: cikmcup
  batch_size: 64
  shuffle: True
  drop_last: False
early_stop:
  patience: 20
  improve_indicator_mode: mean
  the_smaller_the_better: False
federate:
  mode: 'standalone'
  client_num: 13
  total_round_num: 100
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']
trainer:
  type: graphminibatch_trainer
model:
  type: gin
  task: graph
  use_bias: True
  dropout: 0.5
  hidden: 64
grad:
  grad_clip: 0.5
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.1
    weight_decay: 0.
eval:
  freq: 100
  count_flops: False
  metrics: ['imp_ratio']
  report: ['avg']
  best_res_update_round_wise_key: val_avg_loss
finetune:
  before_eval: True
  local_update_steps: 200
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01