# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sqlquery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esqlquery.proto\"/\n\nExpression\x12\x10\n\x08operator\x18\x01 \x01(\t\x12\x0f\n\x07\x65lement\x18\x02 \x03(\t\"\xcd\x01\n\nBasicQuery\x12\x1f\n\nexp_select\x18\x01 \x01(\x0b\x32\x0b.Expression\x12\x1d\n\x08\x65xp_from\x18\x02 \x01(\x0b\x32\x0b.Expression\x12#\n\texp_where\x18\x03 \x01(\x0b\x32\x0b.ExpressionH\x00\x88\x01\x01\x12!\n\x07\x65xp_agg\x18\x04 \x01(\x0b\x32\x0b.ExpressionH\x01\x88\x01\x01\x12\x1d\n\x08\x63hildren\x18\x05 \x03(\x0b\x32\x0b.BasicQueryB\x0c\n\n_exp_whereB\n\n\x08_exp_aggb\x06proto3')



_EXPRESSION = DESCRIPTOR.message_types_by_name['Expression']
_BASICQUERY = DESCRIPTOR.message_types_by_name['BasicQuery']
Expression = _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), {
  'DESCRIPTOR' : _EXPRESSION,
  '__module__' : 'sqlquery_pb2'
  # @@protoc_insertion_point(class_scope:Expression)
  })
_sym_db.RegisterMessage(Expression)

BasicQuery = _reflection.GeneratedProtocolMessageType('BasicQuery', (_message.Message,), {
  'DESCRIPTOR' : _BASICQUERY,
  '__module__' : 'sqlquery_pb2'
  # @@protoc_insertion_point(class_scope:BasicQuery)
  })
_sym_db.RegisterMessage(BasicQuery)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPRESSION._serialized_start=18
  _EXPRESSION._serialized_end=65
  _BASICQUERY._serialized_start=68
  _BASICQUERY._serialized_end=273
# @@protoc_insertion_point(module_scope)
